
SQL_DB_HOST: localhost
SQL_DB_PORT: 3306
SQL_DB_USER: root
SQL_DB_PASS: dongphuong189
MYSQL_DB: baseweb

spring:
  data:
    rest:
      detection-strategy:  ANNOTATED
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 300000
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 1000000
    url: jdbc:mysql://${SQL_DB_HOST}:${SQL_DB_PORT}/${MYSQL_DB}?useUnicode=yes&characterEncoding=UTF-8
    username: ${SQL_DB_USER}
    password: ${SQL_DB_PASS}
  jpa:
    properties:
      hibernate:
        format_sql: true
